language: node_js
node_js:
  - 11.10.0
services:
  - docker
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
env:
  ci: true
script:
  - docker build -t "$DOCKER_USERNAME"/texlive-full .
  - docker images
  - docker run --name latex-action --rm -v "/var/run/docker.sock":"/var/run/docker.sock" -v "$PWD":/root/workspace jefftian/texlive-full:latest "fduthesis.tex" "/root/workspace/test" "arara" "--verbose" "fduthesis"
  - docker push "$DOCKER_USERNAME"/texlive-full
  - docker kill texlive-full || echo "texlive-full killed"
  - docker rm texlive-full || echo "texlive-full removed"
  -  #docker-slim/docker-slim build "$DOCKER_USERNAME"/texlive-full
  - docker images
  -  #docker ps | grep -q texlive-full.slim
  -  #docker push "$DOCKER_USERNAME"/texlive-full.slim
  -  #docker run --name latex-action --rm -v "/var/run/docker.sock":"/var/run/docker.sock" -v "$PWD":/root/workspace jefftian/texlive-full.slim:latest "fduthesis.tex" "/root/workspace/test" "arara" "--verbose" "fduthesis"
