name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
      - name: Compile LaTeX document with pre/post compile actions
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
          pre_compile: |
            rm test.pdf
          post_compile: |
            ls test.pdf
      - name: Compile multiple LaTeX documents
        uses: ./
        with:
          root_file: |
            file1.tex
            file2.tex
          working_directory: test/
      - name: Compile LaTeX document with math symbols
        uses: ./
        with:
          root_file: math.tex
          working_directory: test/
      - name: Compile LaTeX document with biblatex/biber
        uses: ./
        with:
          root_file: biblatex.tex
          working_directory: test/
      - name: Compile LaTeX document with eps figure
        uses: ./
        with:
          root_file: eps.tex
          working_directory: test/
      - name: Compile LaTeX document with minted and lualatex
        uses: ./
        with:
          root_file: minted.tex
          working_directory: test/
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
      - name: Compile LaTeX document with arara and graphviz
        uses: ./
        with:
          root_file: graphviz.tex
          working_directory: test/
          compiler: arara
          args: "--verbose"
      # https://github.com/xu-cheng/latex-action/issues/16
      - name: Test Action with Github Default Template
        uses: ./
        with:
          # The root LaTeX file to be compiled
          root_file: test/test.tex
          # The working directory for the LaTeX engine
          working_directory: # optional
          # The LaTeX engine to be invoked
          compiler: # optional, default is latexmk
          # Extra arguments to be passed to the LaTeX engine
          args: # optional, default is -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          # [Deprecated] Install extra packages by tlmgr
          extra_packages: # optional
          # Install extra packages by apk
          extra_system_packages: # optional
      - name: Test fduthesis
        uses: ./
        with:
          root_file: fduthesis.tex
          working_directory: test/
          compiler: lualatex
          args: "--verbose"
          # Arbitrary bash codes to be executed before compiling LaTeX documents
          pre_compile: # optional
          # Arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: # optional
          # Instruct latexmk to enable --shell-escape
          latexmk_shell_escape: true
          # Instruct latexmk to use LuaLaTeX
          latexmk_use_lualatex: true
          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: false
      - name: Check pdf files
        run: |
          file test/test.pdf | grep -q ' PDF '
          file test/file1.pdf | grep -q ' PDF '
          file test/file2.pdf | grep -q ' PDF '
          file test/math.pdf | grep -q ' PDF '
          file test/biblatex.pdf | grep -q ' PDF '
          file test/eps.pdf | grep -q ' PDF '
          file test/minted.pdf | grep -q ' PDF '
          file test/graphviz.pdf | grep -q ' PDF '
          file test/abc.pdf | grep -q ' PDF '
          file test/fduthesis.pdf | grep -q ' PDF '
      - name: CNAME
        run: |
          rm test/.gitignore
          cp CNAME test/CNAME
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./test
        with:
          emptyCommits: true
          keepFiles: true
          commitMessage: ${{ github.event.head_commit.message }}
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: test
          path: test
        if: always()
